using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;
namespace QLDSV
{
    public partial class FormDiem : Form
    {
        public FormDiem()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // This line of code is generated by Data Source Configuration Wizard
        }
        public static String malop = "";
        String macn = "";
        public static String masv = "";
        public static String mamh = "";
        public static int lan = 0;
        public static float diem = 0;
        private void lOPBindingNavigatorSaveItem_Click(object sender, EventArgs e)
        {
            this.Validate();
            this.bdsLop.EndEdit();
            this.tableAdapterManager.UpdateAll(this.DS);

        }

        private void FormDiem_Load(object sender, EventArgs e)
        {
     
            try
            {
                //groupBox1.Enabled = false;
                //btnGhi.Enabled = false;
               // btnPhuchoi.Enabled = false;
                btnghi.Enabled = false;
                gcdiem.Enabled = false;
                this.lOPTableAdapter.Connection.ConnectionString = Program.connstr;
                this.lOPTableAdapter.Fill(this.DS.LOP);
                this.sINHVIENTableAdapter.Connection.ConnectionString = Program.connstr;
                this.sINHVIENTableAdapter.Fill(this.DS.SINHVIEN);
                //TODO: This line of code loads data into the 'DS.DIEM' table. You can move, or remove it, as needed.
                this.mONHOCTableAdapter.Connection.ConnectionString = Program.connstr;
            // TODO: This line of code loads data into the 'DS.MONHOC' table. You can move, or remove it, as needed.
                this.mONHOCTableAdapter.Fill(this.DS.MONHOC);

                macn = ((DataRowView)bdsLop[bdsLop.Position])["MAKH"].ToString();
                cmbkhoa.DataSource = Program.bds_dspm;
                cmbkhoa.DisplayMember = "TENSITE";
                cmbkhoa.ValueMember = "TENSERVER";
                cmbkhoa.SelectedIndex = Program.mChinhanh;
                if (Program.mGroup == "PGV")
                {
                    cmbkhoa.Enabled = true;

                }
                else cmbkhoa.Enabled = false;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi Reload :" + ex.Message, "", MessageBoxButtons.OK);
                return;
            }
        }

        private void btnThoat_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Close();
        }

        private void cmbkhoa_SelectedIndexChanged_1(object sender, EventArgs e)
        {
            if (cmbkhoa.SelectedValue == null)
            {
                return;
            }
            if (cmbkhoa.SelectedValue.ToString() == "System.Data.DataRowView")
                return;
            Program.servername = cmbkhoa.SelectedValue.ToString();

            if ((cmbkhoa.SelectedIndex != Program.mChinhanh) && (cmbkhoa.SelectedIndex != 2))
            {
                Program.mlogin = Program.remotelogin;
                Program.password = Program.remotepassword;
            }

            else
            {
                Program.mlogin = Program.mloginDN;
                Program.password = Program.passwordDN;
            }
            if (Program.KetNoi() == 0)
                MessageBox.Show("Lỗi kết nối về chi nhánh mới hoặc không có quyền vào chi nhánh", "", MessageBoxButtons.OK);
            else
            {
                this.lOPTableAdapter.Connection.ConnectionString = Program.connstr;
                this.lOPTableAdapter.Fill(this.DS.LOP);
                this.sINHVIENTableAdapter.Connection.ConnectionString = Program.connstr;
                this.sINHVIENTableAdapter.Fill(this.DS.SINHVIEN);
                this.mONHOCTableAdapter.Connection.ConnectionString = Program.connstr;
                this.mONHOCTableAdapter.Fill(this.DS.MONHOC);
   
                macn = ((DataRowView)bdsLop[bdsLop.Position])["MAKH"].ToString();

            }   
        }
       
        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
           
            btnghi.Enabled = true;
            btnphuchoi.Enabled = true;
            btnThoat.Enabled = btnbd.Enabled = btnxem.Enabled = panel1.Enabled = cmbkhoa.Enabled = false;
            gcdiem.Enabled = true;
            bdsnhapdiem.Clear();
            lan = Int32.Parse(spLT.Text);
            if ((lan == 0 || lan >= 3) || diem == null)
            {
                MessageBox.Show("Số lần không thích hợp", "", MessageBoxButtons.OK);
                btnThoat.Enabled = btnxem.Enabled = btnbd.Enabled = panel1.Enabled = cmbkhoa.Enabled = true;
                btnphuchoi.Enabled = gcdiem.Enabled = btnghi.Enabled = false;
                return;
            }
            for (int i = 0; i < bdssv.Count; i++)
            {

                if (cmbmalop.Text == ((DataRowView)bdssv[i])["MALOP"].ToString())
                {

                  
                    BANGDIEM bd = new BANGDIEM();
                    bd.MASV = ((DataRowView)bdssv[i])["MASV"].ToString();
                    bd.HOTEN = (((DataRowView)bdssv[i])["HO"].ToString() + " " + ((DataRowView)bdssv[i])["TEN"].ToString());
                    bdsnhapdiem.Add(bd);
                }
                
            }
            for (int i = 0; i <bdsnhapdiem.Count; i++)
            {
            
                try
                {
                    SqlDataReader myReader;
                    String strLenh = "exec SP_KIEMTRADIEM '" + gcdiem["colmasv", i].Value.ToString() + "','" + cmbMM.Text + "'," + Int32.Parse(spLT.Text) + "";
                    myReader = Program.ExecSqlDataReader(strLenh);
                    if (myReader == null) return;
                    myReader.Read();
                    String kq = myReader.GetString(0);

                    if (kq == "CO")
                    {
                        bdsnhapdiem.RemoveAt(i);
                        i--;
                    }
                    myReader.Close();
                }
                catch (Exception ex)
                {

                    MessageBox.Show("Lỗi load sinh viên.\n" + ex.Message, "", MessageBoxButtons.OK);
                    return;
                }
            }
                if (bdsnhapdiem.Count == 0)
                {
                    MessageBox.Show("Lớp không có sinh viên hoặc tất cả sinh viên lớp này đã có điểm môn này", "", MessageBoxButtons.OK);
                    btnghi.Enabled = false;
                    btnphuchoi.Enabled = false;
                    btnThoat.Enabled = btnbd.Enabled = btnxem.Enabled = panel1.Enabled = cmbkhoa.Enabled = true;
                    gcdiem.Enabled = false;
                    return;
                }
           
        }

        private void cmbmalop_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            int k = 0;
            for (int i = 0; i < bdsnhapdiem.Count; i++)
            {

                masv = gcdiem["colmasv", i].Value.ToString();
                mamh = cmbMM.Text;
                lan = Int32.Parse(spLT.Text);
                diem = float.Parse(gcdiem["coldiem", i].Value.ToString());
                
                Program.capnhat("INSERT INTO DIEM(MASV,MAMH,LAN,DIEM) VALUES('" + masv + "','" + mamh + "'," + lan + "," + diem + ")");
                k = 1;
              
            }
            if (k == 1)
            {
                MessageBox.Show("Cập nhật thành công", "", MessageBoxButtons.OK);
            }
            btnThoat.Enabled = btnxem.Enabled = btnbd.Enabled = panel1.Enabled = cmbkhoa.Enabled = true;
            btnphuchoi.Enabled = gcdiem.Enabled = btnghi.Enabled = false;
        }

        private void btnphuchoi_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
        
            bdsdiem.CancelEdit();
            bdsnhapdiem.Clear();
            btnThoat.Enabled = btnbd.Enabled = btnxem.Enabled = panel1.Enabled = true;
            btnghi.Enabled = btnphuchoi.Enabled = gcdiem.Enabled = false;
        }

        private void btnxem_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Formxemdiem f = new Formxemdiem();
            f.Show();
        }

        private void barButtonItem1_ItemClick_1(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

    }
}
